services:
  - type: web
    name: uniforum-laravel-backend
    runtime: docker
    region: frankfurt
    plan: free
    envVars:
      - key: ML_SERVICE_URL
        value: https://uniforum-ml-service.onrender.com