package Lecturer.Participation;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

public class ParticipationView extends JPanel {

    private String authToken;
    private int groupId;

    public ParticipationView(int groupId, String authToken, Runnable onBackClicked) {
        this.groupId = groupId;
        this.authToken = authToken;

        setLayout(new BorderLayout(0, 20));
        setBackground(new Color(248, 250, 252)); // Light slate background
        setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        // --- TOP HEADER PANEL ---
        JPanel topPanel = new JPanel(new BorderLayout());
        topPanel.setOpaque(false);

        JButton backButton = new JButton("← Back to Group");
        backButton.setForeground(new Color(37, 99, 235)); // Blue text
        backButton.setContentAreaFilled(false);
        backButton.setBorderPainted(false);
        backButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        backButton.addActionListener(e -> onBackClicked.run());

        JLabel titleLabel = new JLabel("Group Participation");
        titleLabel.setFont(new Font("Arial", Font.BOLD, 22));
        titleLabel.setForeground(new Color(30, 41, 59));

        JLabel subtitleLabel = new JLabel("View student participation performance based on configured criteria.");
        subtitleLabel.setForeground(new Color(100, 116, 139));

        JPanel headerTextPanel = new JPanel();
        headerTextPanel.setLayout(new BoxLayout(headerTextPanel, BoxLayout.Y_AXIS));
        headerTextPanel.setOpaque(false);
        headerTextPanel.add(backButton);
        headerTextPanel.add(Box.createVerticalStrut(10));
        headerTextPanel.add(titleLabel);
        headerTextPanel.add(Box.createVerticalStrut(5));
        headerTextPanel.add(subtitleLabel);

        topPanel.add(headerTextPanel, BorderLayout.CENTER);
        add(topPanel, BorderLayout.NORTH);

        // --- CENTER CONTENT CONTAINER ---
        JPanel contentContainer = new JPanel();
        contentContainer.setLayout(new BoxLayout(contentContainer, BoxLayout.Y_AXIS));
        contentContainer.setOpaque(false);

        // 1. Criteria Summary Panel
        JPanel criteriaPanel = createCardPanel("Active Participation Criteria");
        JPanel metricsGrid = new JPanel(new GridLayout(1, 4, 15, 0));
        metricsGrid.setOpaque(false);

        metricsGrid.add(createMetricCard("Questions Asked", "--"));
        metricsGrid.add(createMetricCard("Answers Given", "--"));
        metricsGrid.add(createMetricCard("Helpful Replies", "--"));
        metricsGrid.add(createMetricCard("Resources Shared", "--"));

        criteriaPanel.add(metricsGrid);
        contentContainer.add(criteriaPanel);
        contentContainer.add(Box.createVerticalStrut(20));

        // 2. Student Scores Table Panel
        JPanel tableCard = createCardPanel("Student Participation Scores");
        
        String[] columnNames = {"Student", "Questions", "Answers", "Contributions", "Total Score"};
        Object[][] data = {
            {"Sarah Namukasa", "--", "--", "--", "-- / 100"},
            {"Peter Okello", "--", "--", "--", "-- / 100"}
        };

        DefaultTableModel tableModel = new DefaultTableModel(data, columnNames);
        JTable table = new JTable(tableModel);
        table.setRowHeight(40);
        table.getTableHeader().setBackground(new Color(241, 245, 249));
        table.setShowVerticalLines(false);
        
        JScrollPane tableScrollPane = new JScrollPane(table);
        tableScrollPane.setPreferredSize(new Dimension(0, 150));
        tableScrollPane.setBorder(BorderFactory.createEmptyBorder());

        tableCard.add(tableScrollPane);
        contentContainer.add(tableCard);
        contentContainer.add(Box.createVerticalStrut(20));

        // 3. Information Panel
        JPanel infoCard = createCardPanel("How Scores Are Calculated");
        JLabel infoText = new JLabel("<html>Participation scores are automatically generated by the system based on student engagement within the discussion group.</html>");
        infoText.setForeground(new Color(100, 116, 139));
        infoCard.add(infoText);
        contentContainer.add(infoCard);

        // Wrap content in a scroll pane just in case
        JScrollPane mainScrollPane = new JScrollPane(contentContainer);
        mainScrollPane.setBorder(BorderFactory.createEmptyBorder());
        mainScrollPane.setOpaque(false);
        mainScrollPane.getViewport().setOpaque(false);

        add(mainScrollPane, BorderLayout.CENTER);
    }

    // Helper to style container cards
    private JPanel createCardPanel(String title) {
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.setBackground(Color.WHITE);
        panel.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(226, 232, 240), 1),
            BorderFactory.createEmptyBorder(20, 20, 20, 20)
        ));

        if (title != null && !title.isEmpty()) {
            JLabel titleLbl = new JLabel(title);
            titleLbl.setFont(new Font("Arial", Font.BOLD, 16));
            titleLbl.setForeground(new Color(30, 41, 59));
            panel.add(titleLbl);
            panel.add(Box.createVerticalStrut(15));
        }

        return panel;
    }

    // Helper to style criteria metric squares
    private JPanel createMetricCard(String label, String value) {
        JPanel card = new JPanel();
        card.setLayout(new BoxLayout(card, BoxLayout.Y_AXIS));
        card.setBackground(new Color(239, 246, 255)); // Light blue tint
        card.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));

        JLabel lblTitle = new JLabel(label);
        lblTitle.setForeground(new Color(71, 85, 105));
        lblTitle.setFont(new Font("Arial", Font.PLAIN, 12));

        JLabel lblValue = new JLabel(value);
        lblValue.setForeground(new Color(37, 99, 235));
        lblValue.setFont(new Font("Arial", Font.BOLD, 18));
        lblValue.setAlignmentX(Component.LEFT_ALIGNMENT);

        card.add(lblTitle);
        card.add(Box.createVerticalStrut(8));
        card.add(lblValue);

        return card;
    }
}